language: r
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    env: VDIFFR_RUN_TESTS=true

env:
  global:
  # switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - mgcv
  - testthat
  - ggplot2
  - cowplot
  - vdiffr
  - scam
  - MASS

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always

